# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  # 2022-08-10, spring-boot(micrometer) + actuator + prometheus + grafana
  #   prometheus 启动成功后，可以访问`http://127.0.0.1:9090/targets` 查看
  #   即`http://127.0.0.1:18080/actuator/prometheus`
  - job_name: "spring-boot-micrometer-examples"
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      # 服务在host，不能写成`127.0.0.1`，需要写成"host.docker.internal"
      - targets: ["host.docker.internal:18080"]